# Generated by Django 5.0.4 on 2024-05-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FLAG', models.IntegerField()),
                ('LOCATIONS', models.CharField(max_length=200)),
                ('DENSITY', models.IntegerField()),
                ('QRCODE', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LOCATIONS', models.CharField(max_length=200)),
                ('QRDECODE', models.CharField(max_length=200)),
            ],
        ),
    ]
