# Generated by Django 5.0.4 on 2024-05-04 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVK',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stop', models.CharField(max_length=100)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='COMOS',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stop', models.CharField(max_length=100)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='SHABARI',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Stop', models.CharField(max_length=100)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('LOCATIONS', models.CharField(max_length=200)),
                ('QRDECODE', models.CharField(max_length=200)),
            ],
        ),
    ]
