# Generated by Django 5.0.4 on 2024-05-04 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['-Time'],
            },
        ),
        migrations.CreateModel(
            name='Bus2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['-Time'],
            },
        ),
        migrations.CreateModel(
            name='Bus3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Crowd', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'ordering': ['-Time'],
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Location', models.TextField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
